services:
  parkly:
    build: .
    container_name: parkly
    volumes:
      - parkly_volume:/app
    command: sh -c "cd backend && python -m flask run --host 0.0.0.0 --port 1234"
    ports:
      - "1234:1234"
    depends_on:
      - redis
      - mailhog
    environment:
      - host="0.0.0.0"
      - port=1234
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - mail_server=mailhog
      - mail_port=1025
      - secret_key=${secret_key}
      - CACHE_REDIS_HOST=redis
      - VITE_BASE_URL=http://localhost:1234

  celery_worker:
    build: .
    container_name: parkly_celery_worker
    volumes:
      - parkly_volume:/app
    command: sh -c "cd backend && celery -A celery_worker worker --loglevel=info"
    depends_on:
      - redis
      - parkly
      - mailhog
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - mail_server=mailhog
      - mail_port=1025
      - secret_key=${secret_key}

  celery_beat:
    build: .
    container_name: parkly_celery_beat
    volumes:
      - parkly_volume:/app
    command: sh -c "cd backend && celery -A celery_worker beat --loglevel=info"
    depends_on:
      - redis
      - parkly
      - mailhog
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - mail_server=mailhog
      - mail_port=1025
      - secret_key=${secret_key}

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP

volumes:
  parkly_volume:
