"""empty message

Revision ID: 2d23ab6b21a4
Revises: 
Create Date: 2025-06-26 17:31:01.887236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d23ab6b21a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('parking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reserve_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'parkings', ['parking_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('parking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('slot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'parkings', ['parking_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'slots', ['slot_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('parking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'parkings', ['parking_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'parkings', ['parking_id'], ['id'])
        batch_op.alter_column('parking_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'slots', ['slot_id'], ['id'])
        batch_op.create_foreign_key(None, 'parkings', ['parking_id'], ['id'])
        batch_op.alter_column('slot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('parking_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'parkings', ['parking_id'], ['id'])
        batch_op.alter_column('reserve_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('parking_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
